@startuml

class Git {
  git-prune() - delete unlink object
}

Git -- Object

class Object {
  +hash
  +body
}

class Blob {
}

class Tree {
  mode: 123456
  type
  hash
  name
}

class Commit {
  +hash
  -type
  parent
  author
  commiter
  text
  goHome()
}

class Tag {
}

Object <|--Tree
Object --|> Blob
Object <|--Commit
Object <|--Tag


@enduml
