// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  exports.config = {
    seleniumAddress: 'http://0.0.0.0:4444/wd/hub',
    allScriptsTimeout: 110000,
    baseUrl: "http://localhost:" + (process.env.PORT || "9000"),
    params: '---start-maximized --disable-popup-blocking',
    dfkaljdfa: 'dsf',
    chromeOnly: false,
    specs: ["e2e/**/*.spec.coffee"],
    exclude: [],
    capabilities: {
      browserName: "chrome"
    },
    framework: "jasmine",
    jasmineNodeOpts: {
      defaultTimeoutInterval: 30000
    },
    onPrepare: function() {
      global.by_ = global['by'];
      return global.findBy = global['by'];
    }
  };


  /*
  conf.js PROTRACTOR
  
  exports.config = {
    seleniumAddress: 'http://0.0.0.0:4444/wd/hub'
    baseUrl: 'http://localhost:3000'
    specs: ['tests/e2e/ * * / *.js']
    rootElement: '.ngApp'
    allScriptsTimeout: 60000
    onPrepare: ()->
      global.By = global.by
      global.findBy = global.by
  }
   */

}).call(this);

//# sourceMappingURL=protractor.conf.map
